version: '3.3'

services:
  dawg09postgresdb:
      container_name: dawg09postgresdb
      hostname: dawg09postgresdb
      build:
        context: ../../sql
        dockerfile: ../docker/Dockerfile-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=dawg09
      ports:
        - 5432:5432

        
  battleshipgame-service-1:
    container_name: battleshipgame-service-1
    hostname: battleshipgame-service-1
    build:
      context: .
      dockerfile: ../../docker/Dockerfile-battleshipgame-service
    environment:
      SERVER_PORT: 8081
      JDBC_DATABASE_URL: "jdbc:postgresql://dawg09postgresdb:5432/dawg09?user=postgres&password=postgres"
    depends_on:
      - dawg09postgresdb
    ports:
      - 8081:8081

  battleshipgame-service-2:
    container_name: battleshipgame-service-2
    hostname: battleshipgame-service-2
    build:
      context: .
      dockerfile: ../../docker/Dockerfile-battleshipgame-service
    environment:
      SERVER_PORT: 8082
      JDBC_DATABASE_URL: "jdbc:postgresql://dawg09postgresdb:5432/dawg09?user=postgres&password=postgres"
    depends_on:
      - dawg09postgresdb
    ports:
      - 8082:8082

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/conf/mime.types
      - ../js/dist/main.js:/etc/nginx/html/main.js
      - ../js/public:/etc/nginx/html/

    depends_on:
      - battleshipgame-service-1
      - battleshipgame-service-2


